config/routes.rb
Rails.application.routes.draw do
  # uses custom controller for registrations
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'welcome#index'
  resources :companies 
  resources :jobs
  resources :applies
  resources :tags
  resources :posts

  # resources :users, only: [:edit_password]

  # Other non-resourceful routes
  get "/recruiter", :to => redirect("/recruiter.html")
  get 'search', to: 'search#search'
  get '/users/edit_password', to: 'user#edit_password'

  get 'static_pages/adminpanel'

  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/feedback'

  get 'static_pages/press'

  get 'static_pages/howitworks'

  get 'static_pages/careers'

  get 'static_pages/product'

  get 'category', :to => 'jobs#category'
end

app/models/job.rb
require 'elasticsearch/model'

class Job < ActiveRecord::Base
	belongs_to :company
	has_many :applies, dependent: :destroy

	validates :title, presence: true
	validates_uniqueness_of :title, scope: :company_id

	has_many :taggings, dependent: :destroy
	has_many :tags, :through => :taggings
	has_many :location_relationship

	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	def tag_list
		tags.join ", "
	end

	def tag_list=(tags_string)
	  tag_names = tags_string.split(",").collect{|s| s.strip}.uniq
	  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
	  self.tags = new_or_found_tags
	end

	def self.search(query)
	  __elasticsearch__.search(
		{
			from: 0, size: 500,
			query: {
				function_score:{
					functions: [{
						gauss: {
							created_at: {
								origin: 'now',
								scale: '3d',
								offset: '2d',
								decay: 0.95
							}
						}
					}],
					query: {
						multi_match: {
							query: query,
							fields: ['title^3', 'description', 'qualification', 'location^3']
						}
					}
				}
			}
		}
	  )
	end

	settings index: { number_of_shards: 1 } do
	  mappings dynamic: 'false' do
	    indexes :title, analyzer: 'english'
	    indexes :description, analyzer: 'english'
			indexes :qualification, analyzer: 'english'
			indexes :location, analyzer: 'english'
			indexes :created_at, type: 'date'
		end
	end
end

# Delete the previous jobs index in Elasticsearch
Job.__elasticsearch__.client.indices.delete index: Job.index_name rescue nil

# Create the new index with the new mapping
Job.__elasticsearch__.client.indices.create \
  index: Job.index_name,
  body: { settings: Job.settings.to_hash, mappings: Job.mappings.to_hash }

# Index all job records from the DB to Elasticsearch
Job.import force: true

app/controllers/jobs_controller.rb
require 'will_paginate'
class JobsController < ApplicationController
	include ApplicationHelper
	before_action :require_admin, :only => [:new, :update, :create, :edit]
	def index
		@jobs = []
		@paginate = false
		if params[:q].nil? || params[:q] == ""
    	@jobs = Job.order("created_at DESC").paginate :page => params[:page]
  		@paginate = true
  	else
    	@jobs = Job.search(params[:q]).page(params[:page]).records
    	@paginate = false
  	end
	end

	def show
		@job = Job.find(params[:id])
		@apply_link
		if user_signed_in?
			@apply_link = new_apply_path(@job)
		else
			@apply_link = new_user_session_path
		end
	end

	def new
		@job = Job.new
		@cid = params[:format]
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		@job.update(job_params)
		@job =  Job.find(params[:id])
		if params[:index]
			if @job.tag_list == job_params[:tag_list]
				flash[:success] = "Assigned Category '#{@job.tag_list}'"
			else
				flash[:error] = "Error. Did not assign category."
			end
			redirect_to "/category?index=#{params[:index]}"
		else
			redirect_to job_path(@job)
		end
	end

	def create
		@job = Job.new(job_params)
		@job.save
		#if generated, show new, else go back to form
		# note this part should be reworked with flash
		if(not(@job.new_record?))
			redirect_to job_path(@job)
		#else
		#	redirect_to new_job_path
		end
	end

	def category
		if params[:index]
			@index = params[:index].to_i
		end
		@index ||= 0
		if @index >= Job.count
			redirect_to '/youredone'
		end
		@job = Job.all[@index]
	end

	private
	def job_params
		params.require(:job).permit(:title, :description, :qualification, :company_id, :tag_list)
	end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_apply_buttons.html.erb
<% if @job.created_at < 3.months.ago %>
  <a href="#" class="btn btn-danger btn-lg btn-block">EXPIRED</a>
<% elsif current_user %>

  <a href="<%=@job.source%>" class="btn btn-primary btn-lg btn-block">Apply
  </a>

<% else %>
  <% session[:job_redirect] = @job.id %>
  <a href="<%=new_user_registration_path%>" class="btn btn-primary btn-lg btn-block">Apply
  </a>
<!-- TODO, redirect back to this page after resume upload -->
<% end %>

app/views/jobs/_edit_job_link.html.erb
<p><%= link_to "Edit this Job.", edit_job_path(@job) %> (should be visible only to owners of a position)</p>
	<p><%= link_to "<<< List of jobs", jobs_path %></p>

	<h3>Current Applicants</h3> (should be visible only to owners of a position)
	<ul>
		<% @job.applies.each do |apply| %>
			<li>
				<%= link_to apply.user.email, apply_path(apply.id) %>
			</li>
		<% end %>
	</ul>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %> 
<ul>
	<!-- error handling -->
	<% @job.errors.full_messages.each do |error| %> 
	<li><%= error %></li>
	<% end %>
</ul>
<p>
	<%= f.label :title %><br />
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</p>
<p>
	<%= f.label :qualification %><br />
	<%= f.text_area :qualification %>
</p>

<p>
	<%= f.submit %>
</p>
<% end %>

app/views/jobs/_job.html.slim
li.job
  .media
    .media-left
      - if job.company.present?
        a href="#{job_path(job)}"
          = image_tag job.company.logo.url(:thumb), class: "company-thumbnail"
    .media-body
      h4.media-heading
        = link_to job.title, job_path(job)
      - if job.company.present?
        => link_to job.company.name, company_path(job.company_id)
      - else
        | (no associated company)
      - if job.location != nil
        = "| "
        span.location= job.location
      .timestamp
        = "Posted #{time_ago_in_words(job.created_at)} ago "
        - if(job.created_at <= 1.months.ago)
          span.label.label-danger OLD
        - elsif(job.created_at > 3.days.ago)
          span.label.label-success NEW

app/views/jobs/_job_info.html.erb
<%if @job.description != nil and @job.description != "" %>
<div class="panel panel-default">
	<div class="panel-heading"><h3>Job Description</h3></div>
	<div class ="panel-body"><%= @job.description.html_safe %></div>
</div>
<%end%>

<%if @job.qualification != nil and @job.qualification != "" %>
<div class="panel panel-default">
	<div class="panel-heading">
	<h3>Key Requirements</h3>
	</div>
	<div class="panel-body"><%= @job.qualification.html_safe %></div>
</div>
<%end%>

app/views/jobs/_jobs_list.html.slim
.row
  .col-lg-2

  .col-lg-8
    
    - if @posts.empty?
      h1 No Search Results!
    - else 
      h1 Available Jobs 
      h3
        = "Search: #{params[:q]}" if !params[:q].nil? && params[:q]!=""
      = will_paginate @posts, renderer: BootstrapPagination::Rails
      ul#posts
        = render @posts
      = will_paginate @posts, renderer: BootstrapPagination::Rails
  .col-lg-2

app/views/jobs/_jumbotron_info.html.erb
<div class="jumbotron">
<h1><%= @job.title %></h1>
<p>
<% if(@job.company_id != nil)%>
	<p><span class="glyphicon glyphicon-globe"></span>
	<% @c_name = Company.find(@job.company_id).name%>
 	<a href="<%=company_path(@job.company_id)%>"><%=@c_name%></a> </p>
<% end %>
<% if(@job.location != nil)%>
	<p><span class="glyphicon glyphicon-map-marker"></span> <%= @job.location %></p>
<% end %>
</p>
<p><span class="glyphicon glyphicon-time"></span>
<%= @job.created_at.strftime("%Y-%m-%d, %T") %></p>

<%= render :partial => "/jobs/apply_buttons" %>
</div>

app/views/jobs/_new_button.html.erb
	<a href="<%=new_job_path()%>" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-pencil"></span> New
	</a>

app/views/jobs/_ready_to_apply.html.slim
h4
  ="Ready to apply "
  span.label.label-info FREE
p.subtext Oil&Gas Job Hunting is now seamless.
p.subtext All on one site.
p.subtext Receive free job notification by signing up.
- if signed_in?
  = link_to "Edit My Profile", edit_user_registration_path, class: 'btn btn-success wide'
- else
  = link_to "Create My Profile", new_user_registration_path, class: 'btn btn-success wide'

app/views/jobs/category.html.erb
<br>

<div class="container top">
  <h1> Categorizer for Job ID: <%=@job.id%> and index: <%=@index%></h1>
  <%= form_for @job do |f|%>
  <%= f.select :tag_list, options_for_select(["Project Management",
  "Construction",
  "Drilling & Completions",
  "Finance & Accounting",
  "Health/Safety/Environment",
  "IT/HR/Training/Analyst/Admin",
  "Maintenance/Inspection/Commissioning",
  "Management & Legal",
  "Facilities/Midstream/Pipelines",
  "Oilfield Services",
  "Other Engineering & Science",
  "Contracts/Procurement/Supply Chain & Logisitics",
  "Production & Operations",
  "Reservoir & Geoscience",
  "Sales/Marketing/Business Development",
  "Trades",
  "Refining & Petrochemical",
  "Offshore Specific",
  "Other",
  "Remove",
  ""].sort)%>
  <%= hidden_field_tag 'index', @index+1  %>
  <%= f.submit "Submit", :class => "btn-lg btn-primary" %>
  <%end%>

  <br>
  <h3>Current Category: <%= @job.tag_list == "" ? "(None)" : @job.tag_list %> </h3>
  <a class="btn btn-primary" href="/category?index=<%= @index + 1 %>">KEEP CURRENT CATEGORY</a>
  <br>
  <br>
<%= render :partial => '/jobs/jumbotron_info' %>
<%= render :partial => '/jobs/job_info' %>
</div>

app/views/jobs/edit.html.erb
<h1>Edit Job Posting</h1>
<%= form_for(@job) do |f| %>
<ul>
	<!-- error handling -->
	<% @job.errors.full_messages.each do |error| %> 
	<li><%= error %></li>
	<% end %>
</ul>
<p>
	<%= f.label :title %><br />
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</p>
<p>
	<%= f.label :qualification %><br />
	<%= f.text_area :qualification %>
</p>
<p>
	<%= f.label :company_id %><br/>
	<%= f.text_field :company_id %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/jobs/index.html.erb
<div class="container">
	<h1 class="text-center">Start Searching for Jobs by Title or Location</h1> 
	<br>
	<form method="get" accept-charset="UTF-8" action="/jobs">
	<div class="input-group input-group-lg">
		<input id="q" name="q" type="text" class="form-control" placeholder="Search job...">
		<span class="input-group-btn">
			<input class="btn btn-primary" type="submit" value="Find Job"><span class="glyphicon glyphicon-search"></span></input>
		</span>
	</div><!-- /input-group -->
	</form>
	<br>
	<hr>
	<%=render :partial => "jobs_list"%>

</div>

app/views/jobs/new.html.erb
<h1>New Job Posting</h1>
<%= form_for(@job) do |f| %>
<%= f.hidden_field :company_id, :value => @cid %>
<ul>
	<!-- error handling -->
	<% @job.errors.full_messages.each do |error| %> 
	<li><%= error %></li>
	<% end %>
</ul>
<p>
	<%= f.label :title %><br />
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</p>
<p>
	<%= f.label :qualification %><br />
	<%= f.text_area :qualification %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/jobs/show.html.erb
<br>
<div class="container" >

			<%= render :partial => "jumbotron_info"%>

			<%=render :partial => "job_info"%>

			<%= render :partial => "apply_buttons" %>

</div>
<br>