config/routes.rb
Rails.application.routes.draw do
  # uses custom controller for registrations
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'welcome#index'
  resources :companies 
  resources :jobs
  resources :applies
  resources :tags
  resources :posts

  # resources :users, only: [:edit_password]

  # Other non-resourceful routes
  get "/recruiter", :to => redirect("/recruiter.html")
  get 'search', to: 'search#search'
  get '/users/edit_password', to: 'user#edit_password'

  get 'static_pages/adminpanel'

  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/feedback'

  get 'static_pages/press'

  get 'static_pages/howitworks'

  get 'static_pages/careers'

  get 'static_pages/product'

  get 'category', :to => 'jobs#category'
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :jobs, dependent: :destroy
  has_many :posts, dependent: :destroy
	#checks if company name exists
	validates :name, uniqueness: true, presence: true
	before_create do
		self.description ||= ""
		self.link ||= ""
	end
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  attr_reader :logo_remote_url

  def logo_remote_url=(url_value)
    if url_value.present?
      self.logo = URI.parse(url_value)
      # Assuming url_value is http://example.com/photos/face.png
      # avatar_file_name == "face.png"
      # avatar_content_type == "image/png"
      @logo_remote_url = url_value
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include ApplicationHelper
  before_action :require_admin, :only => [:new, :update, :create, :edit]
  def index
		# join returns all companies with jobs, group return single company object for each id
    # counts the number of jobs per id and orders company objects in descending
    @companies = Company.joins(:jobs).group("companies.id").order("count(companies.id) DESC")
		@companies = @companies.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)
		@company.save
		redirect_to company_path(@company)
	end

	def edit
		@company = Company.find(params[:id])
	end

	def show
		@company = Company.find(params[:id])
		@jobs = @company.jobs.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
		# @paginate = true
	end

	#Update refers to the SQL operation
	def update
		@company = Company.find(params[:id])
		@company.update(company_params)
		redirect_to company_path(@company)
	end

	def company_params
		params.require(:company).permit(:name,:description,:link, :logo_remote_url, :logo)
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.slim
li.job
  .media
    .media-left
      = image_tag company.logo.url(:thumb), class: "company-thumbnail"
    .media-body
      h4.media-heading
        = link_to company.name, company_path(company)
      p
        - if company.description.length > 200
          = company.description[0...199].html_safe
          |...
        - else
          = company.description.html_safe

app/views/companies/edit.html.slim
.row
  .col-lg-12: .block
    h2 Edit #{@company.name}
    = form_for @company, method: :put do |f|
      - @company.errors.full_messages.each do |error|
        li= error
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'
      .form-group
        = f.label :image, "Image"
        = render :partial => 'shared/image_upload', :locals => { :f => f }
      => f.submit "Update", class: 'btn btn-primary'

app/views/companies/index.html.erb
<div class="container">
<h1 style="text-align: center;">List of Companies</h1>
<hr>
<ul class="media-list">
<% @companies.each do |company| %>
	<%= render company %>
	<% end %>
	<%=will_paginate @companies, renderer: BootstrapPagination::Rails%>
</ul>
<% if current_user.present? %>
<% if current_user.admin? %>
<%= link_to "new company", new_company_path() %> (Placeholder for now, link accessible to admins only)
<%end%>
<%end%>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>
<%= form_for(@company) do |f| %> 
<ul>
	<!-- error handling -->
	<% @company.errors.full_messages.each do |error| %> 
	<li><%= error %></li>
	<% end %>
</ul>
<p>
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</p>
<p>
	<%= f.label :link %><br />
	<%= f.text_field :link %>
</p>

<p>
	<%= f.submit %>
</p>
<% end %>

app/views/companies/show.html.erb
<div class="container">
	<div class="jumbotron">
	<div class="media">
		<div class="media-left">
			<%= image_tag @company.logo.url(:thumb), class: "jumbo-image"%>
		</div>
		<div class="media-body">
			<h1 class="media-heading"><%= @company.name %></h1>
		</div>
	</div>

<% if current_user.present? %>
<% if current_user.admin? %>
<p><%= link_to "Edit Profile.", edit_company_path(@company) %> (This link is only seen if admin or on an associated user account)</p>
<p><%= link_to "Post Job.", new_job_path(@company) %></p>
<%end%>
<%end%>
<p><%= @company.description.html_safe %></p>
</div>
<!-- Shows job postings for company if existing -->
<% if (@company.jobs.length > 0) %>
	<%= render :partial => "/jobs/jobs_list"%>
<% else %>
	<h3>No Job Postings for this company yet!</h3>
<% end %>
<br>
</div>