config/routes.rb
Rails.application.routes.draw do
  # uses custom controller for registrations
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'welcome#index'
  resources :companies 
  resources :jobs
  resources :applies
  resources :tags
  resources :posts

  # resources :users, only: [:edit_password]

  # Other non-resourceful routes
  get "/recruiter", :to => redirect("/recruiter.html")
  get 'search', to: 'search#search'
  get '/users/edit_password', to: 'user#edit_password'

  get 'static_pages/adminpanel'

  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/feedback'

  get 'static_pages/press'

  get 'static_pages/howitworks'

  get 'static_pages/careers'

  get 'static_pages/product'

  get 'category', :to => 'jobs#category'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings, dependent: :destroy
	has_many :jobs, through: :taggings
	validates :name, uniqueness: { case_sensitive: false }

	def to_s
		name
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find(params[:id])
	end
	def index
		@tags = Tag.all
	end
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/tags/index.html.slim
h1 All tags
ul
  - @tags.each do |tag|
    li
      = link_to "#{tag.name} (#{tag.jobs.size})", tag_path(tag)

app/views/tags/show.html.erb
<h1>Jobs tagged with <%=@tag.name%></h1>
<ul>
	<% @tag.jobs.each do |job| %>
	<li><%= link_to job.title, job_path(job) %></li>
	<% end %>
</ul>
<br/>