config/routes.rb
Rails.application.routes.draw do
  # uses custom controller for registrations
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'welcome#index'
  resources :companies 
  resources :jobs
  resources :applies
  resources :tags
  resources :posts

  # resources :users, only: [:edit_password]

  # Other non-resourceful routes
  get "/recruiter", :to => redirect("/recruiter.html")
  get 'search', to: 'search#search'
  get '/users/edit_password', to: 'user#edit_password'

  get 'static_pages/adminpanel'

  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/feedback'

  get 'static_pages/press'

  get 'static_pages/howitworks'

  get 'static_pages/careers'

  get 'static_pages/product'

  get 'category', :to => 'jobs#category'
end

app/models/apply.rb
class Apply < ActiveRecord::Base
	belongs_to :user
	belongs_to :job
  belongs_to :post
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :jobs, dependent: :destroy
  has_many :posts, dependent: :destroy
	#checks if company name exists
	validates :name, uniqueness: true, presence: true
	before_create do
		self.description ||= ""
		self.link ||= ""
	end
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  attr_reader :logo_remote_url

  def logo_remote_url=(url_value)
    if url_value.present?
      self.logo = URI.parse(url_value)
      # Assuming url_value is http://example.com/photos/face.png
      # avatar_file_name == "face.png"
      # avatar_content_type == "image/png"
      @logo_remote_url = url_value
    end
  end

end

app/models/job.rb
require 'elasticsearch/model'

class Job < ActiveRecord::Base
	belongs_to :company
	has_many :applies, dependent: :destroy

	validates :title, presence: true
	validates_uniqueness_of :title, scope: :company_id

	has_many :taggings, dependent: :destroy
	has_many :tags, :through => :taggings
	has_many :location_relationship

	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	def tag_list
		tags.join ", "
	end

	def tag_list=(tags_string)
	  tag_names = tags_string.split(",").collect{|s| s.strip}.uniq
	  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
	  self.tags = new_or_found_tags
	end

	def self.search(query)
	  __elasticsearch__.search(
		{
			from: 0, size: 500,
			query: {
				function_score:{
					functions: [{
						gauss: {
							created_at: {
								origin: 'now',
								scale: '3d',
								offset: '2d',
								decay: 0.95
							}
						}
					}],
					query: {
						multi_match: {
							query: query,
							fields: ['title^3', 'description', 'qualification', 'location^3']
						}
					}
				}
			}
		}
	  )
	end

	settings index: { number_of_shards: 1 } do
	  mappings dynamic: 'false' do
	    indexes :title, analyzer: 'english'
	    indexes :description, analyzer: 'english'
			indexes :qualification, analyzer: 'english'
			indexes :location, analyzer: 'english'
			indexes :created_at, type: 'date'
		end
	end
end

# Delete the previous jobs index in Elasticsearch
Job.__elasticsearch__.client.indices.delete index: Job.index_name rescue nil

# Create the new index with the new mapping
Job.__elasticsearch__.client.indices.create \
  index: Job.index_name,
  body: { settings: Job.settings.to_hash, mappings: Job.mappings.to_hash }

# Index all job records from the DB to Elasticsearch
Job.import force: true

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :location_relationships
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :company
  belongs_to :publisher, class_name: :User
  has_many :applies

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

def self.search(query)
    __elasticsearch__.search(
    {
      from: 0, size: 500,
      query: {
        function_score:{
          functions: [{
            gauss: {
              created_at: {
                origin: 'now',
                scale: '3d',
                offset: '2d',
                decay: 0.95
              }
            }
          }],
          query: {
            multi_match: {
              query: query,
              fields: ['title^3', 'description', 'qualification', 'location^3']
            }
          }
        }
      }
    }
    )
  end
end

# Delete the previous posts index in Elasticsearch
Post.__elasticsearch__.client.indices.delete index: Post.index_name rescue nil

# Create the new index with the new mapping
Post.__elasticsearch__.client.indices.create \
  index: Post.index_name,
  body: { settings: Post.settings.to_hash, mappings: Post.mappings.to_hash }

# Index all Post records from the DB to Elasticsearch
Post.import force: true

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings, dependent: :destroy
	has_many :jobs, through: :taggings
	validates :name, uniqueness: { case_sensitive: false }

	def to_s
		name
	end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
	belongs_to :job
	belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :applies, dependent: :destroy
  has_many :watchlists, dependent: :destroy
  has_many :posts, foreign_key: :publisher_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # paperclip, aws, upload resume document
  has_attached_file :resume
  validates_attachment :resume, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  # TODO look at the above validation, format is fucked up

  # removed password confirmation
  validates_confirmation_of :password
end

app/models/watchlist.rb
class Watchlist < ActiveRecord::Base
	belongs_to :user
	belongs_to :job
end

app/controllers/jobs_controller.rb
require 'will_paginate'
class JobsController < ApplicationController
	include ApplicationHelper
	before_action :require_admin, :only => [:new, :update, :create, :edit]
	def index
		@jobs = []
		@paginate = false
		if params[:q].nil? || params[:q] == ""
    	@jobs = Job.order("created_at DESC").paginate :page => params[:page]
  		@paginate = true
  	else
    	@jobs = Job.search(params[:q]).page(params[:page]).records
    	@paginate = false
  	end
	end

	def show
		@job = Job.find(params[:id])
		@apply_link
		if user_signed_in?
			@apply_link = new_apply_path(@job)
		else
			@apply_link = new_user_session_path
		end
	end

	def new
		@job = Job.new
		@cid = params[:format]
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		@job.update(job_params)
		@job =  Job.find(params[:id])
		if params[:index]
			if @job.tag_list == job_params[:tag_list]
				flash[:success] = "Assigned Category '#{@job.tag_list}'"
			else
				flash[:error] = "Error. Did not assign category."
			end
			redirect_to "/category?index=#{params[:index]}"
		else
			redirect_to job_path(@job)
		end
	end

	def create
		@job = Job.new(job_params)
		@job.save
		#if generated, show new, else go back to form
		# note this part should be reworked with flash
		if(not(@job.new_record?))
			redirect_to job_path(@job)
		#else
		#	redirect_to new_job_path
		end
	end

	def category
		if params[:index]
			@index = params[:index].to_i
		end
		@index ||= 0
		if @index >= Job.count
			redirect_to '/youredone'
		end
		@job = Job.all[@index]
	end

	private
	def job_params
		params.require(:job).permit(:title, :description, :qualification, :company_id, :tag_list)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find(params[:id])
	end
	def index
		@tags = Tag.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    self.admin == true
  end

  def require_admin
    unless current_user && current_user.admin?
      flash[:error] = "You must be an admin to access this."
      redirect_to new_user_session_path
    end
  end
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_search.html.erb
  <form class="navbar-form navbar-right" role="search">
        <div class="input-group">
    <input type="text" class="form-control" placeholder="Search job...">
    <span class="input-group-btn">
      <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
    </span>
  </div><!-- /input-group -->
      </form>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="The largest collection of oil and gas jobs, find companies looking to hire and apply and connect. Join our network today!">
   <%= csrf_meta_tags %>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

 <link rel="shortcut icon" type="image/png" href="<%= asset_path 'favicon.png'%>"/>

  <title>PetroRecruit</title>
</head>
<body>
  <nav>
        <div class="wrapper">
          <a href="<%= root_path %>">
            <%= image_tag "wordlogo.png", id: "logo", alt: "PetroRecruit", width: "320px", height: "50px" %>
          </a>
            <div id="menu">
                &#9776;
            </div>
            <div id="navbtns">
                <% if user_signed_in? %>
                  <a class="btn btn-default btn-lg"  style="bottom: 15px;"  href="<%=destroy_user_session_path%>" rel="nofollow" data-method="delete">Logout</a>
                  <a class="btn btn-primary btn-lg"  style="bottom: 15px;"  href="<%= edit_user_registration_path%>">Profile</a>
                <% else %>
                <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg", style: "bottom: 15px;" %>
                <a class="btn btn-primary btn-lg" style="bottom: 15px;" href="<%= new_user_registration_path%>">Sign Up</a>
                <% end %>
                <a class="btn btn-primary btn-lg" style="bottom: 15px;background-color:#3f81c7; border-color:#3f81c7" href="<%=  new_post_path %>">Post A Job</a>

                <a id="orange" href="<%=companies_path()%>">Companies</a>
                <a id="orange" href="<%=posts_path%>">Find A Job</a>

            </div>
        </div>
    </nav>


<div id="top">

  <% flash.each do |key, value| %>
    <div class="alert <%= key %> overlay">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>
  <div id="footer">
      <div class="wrapper">
        <div class="container">
          <span id="created"><a id="orange" href="mailto:contact@petrorecruit.ca">Contact Us</a> | PetroRecruit ©</span>
        </div>
      </div>
  </div>
</body>
</html>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<script src="https://cdn.smooch.io/smooch.min.js"></script>

<script>
    Smooch.init({appToken: '4ihr4lgh26bf7pcm7qf3dclka'}).then(function() {
      Smooch.updateUser({
        givenName: '<%= user_signed_in? ? "User ID:#{current_user.id}" : "ANONYMOUS" %>',
        email: '<%= user_signed_in? ? current_user.email : "ANONYMOUS" %>'
      })
    });
</script>

app/views/shared/_image_upload.html.slim
ul.nav.nav-pills
  li.active
    a data-toggle="tab" href="#upload-image" Upload
  li
    a data-toggle="tab" href="#remote-image" Remote URL
br
.tab-content
  #upload-image.tab-pane.active
    = f.file_field :logo
  #remote-image.tab-pane
    = f.text_field :logo_remote_url, class: 'form-control', placeholder: 'e.g. http://example.com/image.gif'